#!/usr/bin/perl -w

use strict;

################
# Rotate an image file 90 degrees.

foreach my $file (@ARGV)
	{
	if(! -f $file)
		{
		die "Bad file $file\n"; 
		}
	if($file =~ /\//)
		{
		die "No path support. You must be in same directory as the file.\n";
		}
	if(! -d "raw")
		{
		mkdir("raw");
		}
	system("/bin/mv", $file, "raw/");
	my $filec = $file;
	$filec =~ s/\.jpg/_r\.jpg/;
	system("convert", "-rotate", "90", "raw/$file", $filec);
	print "$file => $filec\n";
	}

