#!/usr/bin/perl -w

use DBI;

main();

#######################

sub main
{
my $dbconf = "DBI:mysqlEmb:database=amarok;mysql_embedded_options=--basedir=/home/pgunn/.kde/share/apps/amarok";
$dbh = DBI->connect($dbconf, "amarok", "");

}

